#!/usr/bin/env python3

import os
import sys
import subprocess


def main():

    if len(sys.argv) < 2:
        print("V-gTK")
        print("")
        print("Usage:")
        print("  vgtk <command> [arguments]")
        print("")
        print("Example:")
        print("  vgtk DownloadGFF --help")
        print("  vgtk GenBankParser --help")
        sys.exit(1)

    command = sys.argv[1]

    if command.endswith(".py"):
        command = command[:-3]

    scripts_dir = os.path.join(
        sys.prefix,
        "share",
        "vgtk",
        "scripts"
    )

    script_path = os.path.join(
        scripts_dir,
        command + ".py"
    )

    if not os.path.isfile(script_path):
        print(f"V-gTK command not found: {command}")
        sys.exit(1)

    cmd = [
        sys.executable,
        script_path
    ] + sys.argv[2:]

    result = subprocess.run(cmd)

    sys.exit(result.returncode)


if __name__ == "__main__":
    main()
